# Generated by Django 5.1.5 on 2025-01-26 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("brokers", "0002_currency_broker_country_broker_currency"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="broker",
            options={"ordering": ["id"]},
        ),
    ]
