# Generated by Django 5.1.5 on 2025-01-24 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tickers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeclaredDividend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value_per_share",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("payment_date", models.DateField()),
                (
                    "ticker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="declared_dividens",
                        to="tickers.ticker",
                    ),
                ),
            ],
            options={
                "ordering": ["-payment_date"],
            },
        ),
        migrations.CreateModel(
            name="Dividend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date", models.DateField()),
                ("quantity_quote", models.IntegerField()),
                ("total_value", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "ticker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dividens",
                        to="tickers.ticker",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
