# Generated by Django 5.1.5 on 2025-01-30 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dividends", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dividend",
            name="total_value",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
