# Generated by Django 5.1.5 on 2025-01-30 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dividends", "0002_alter_dividend_total_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dividend",
            name="quantity_quote",
            field=models.IntegerField(default=0),
        ),
    ]
