# Generated by Django 5.1.5 on 2025-02-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dividends", "0003_alter_dividend_quantity_quote"),
    ]

    operations = [
        migrations.AddField(
            model_name="dividend",
            name="income_type",
            field=models.CharField(
                choices=[
                    ("D", "Dividendo"),
                    ("J", "Juros de Capital Próprio"),
                    ("A", "Amortização"),
                ],
                default="D",
                max_length=20,
            ),
        ),
    ]
