# Generated by Django 5.1.5 on 2025-02-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dividends", "0004_dividend_income_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dividend",
            name="value",
            field=models.DecimalField(decimal_places=10, max_digits=12),
        ),
    ]
