# Generated by Django 5.1.5 on 2025-02-12 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dividends", "0005_alter_dividend_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="dividend",
            name="currency",
            field=models.CharField(
                choices=[("BRL", "Real"), ("USD", "Dólar")], default="BRL", max_length=3
            ),
        ),
    ]
