# Generated by Django 6.0.1 on 2026-01-30 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dividends", "0006_dividend_currency"),
        ("tickers", "0002_alter_ticker_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="declareddividend",
            name="payment_date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="dividend",
            name="date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="dividend",
            name="income_type",
            field=models.CharField(
                choices=[
                    ("D", "Dividendos"),
                    ("J", "Juros de Capital Próprio"),
                    ("A", "Amortização"),
                ],
                default="D",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="declareddividend",
            index=models.Index(
                fields=["ticker", "payment_date"], name="declared_div_ticker_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dividend",
            index=models.Index(
                fields=["ticker", "date"], name="dividend_ticker_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dividend",
            index=models.Index(
                fields=["date", "currency"], name="dividend_date_currency_idx"
            ),
        ),
    ]
