# Generated by Django 6.0.1 on 2026-01-30 08:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dividends", "0007_alter_declareddividend_payment_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dividend",
            name="quantity_quote",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="A quantidade nao pode ser negativa."
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="dividend",
            name="value",
            field=models.DecimalField(
                decimal_places=10,
                max_digits=12,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="O valor nao pode ser negativo."
                    )
                ],
            ),
        ),
    ]
