# Generated by Django 6.0.1 on 2026-01-30 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dividends", "0008_alter_dividend_quantity_quote_alter_dividend_value"),
        ("tickers", "0003_alter_ticker_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="declareddividend",
            name="ticker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="declared_dividends",
                to="tickers.ticker",
            ),
        ),
        migrations.AlterField(
            model_name="dividend",
            name="ticker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dividends",
                to="tickers.ticker",
            ),
        ),
    ]
