# Generated by Django 5.1.5 on 2025-02-15 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brokers", "0003_alter_broker_options"),
        ("outflows", "0002_alter_outflow_total_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outflow",
            name="broker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="outflows",
                to="brokers.broker",
            ),
        ),
    ]
