# Generated by Django 6.0.1 on 2026-01-30 08:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "outflows",
            "0004_alter_outflow_date_outflow_outflow_ticker_date_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="outflow",
            name="cost_price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(
                        0.01, message="O preco deve ser maior que zero."
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="outflow",
            name="quantity",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        1, message="A quantidade deve ser pelo menos 1."
                    )
                ]
            ),
        ),
        migrations.AlterField(
            model_name="outflow",
            name="tax",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="A taxa nao pode ser negativa."
                    )
                ],
            ),
        ),
    ]
