# Generated by Django 5.1.5 on 2025-02-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticker",
            name="name",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
