# Generated by Django 6.0.1 on 2026-01-30 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brokers", "0003_alter_broker_options"),
        ("tickers", "0002_alter_ticker_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticker",
            name="currency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tickers",
                to="brokers.currency",
            ),
        ),
    ]
