# Generated by Django 5.1.5 on 2025-01-31 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brokers", "0003_alter_broker_options"),
        ("inflows", "0003_inflow_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inflow",
            name="broker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inflows",
                to="brokers.broker",
            ),
        ),
    ]
