# Generated by Django 5.1.5 on 2025-02-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inflows", "0004_alter_inflow_broker"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inflow",
            name="type",
            field=models.CharField(
                choices=[("Compra", "Compra"), ("Subscrição", "Subscrição")],
                default="Compra",
                max_length=20,
            ),
        ),
    ]
