# Generated by Django 6.0.1 on 2026-01-30 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brokers", "0003_alter_broker_options"),
        ("inflows", "0005_alter_inflow_type"),
        ("tickers", "0002_alter_ticker_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inflow",
            name="date",
            field=models.DateField(db_index=True),
        ),
        migrations.AddIndex(
            model_name="inflow",
            index=models.Index(
                fields=["ticker", "date"], name="inflow_ticker_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inflow",
            index=models.Index(
                fields=["broker", "date"], name="inflow_broker_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inflow",
            index=models.Index(
                fields=["ticker", "broker"], name="inflow_ticker_broker_idx"
            ),
        ),
    ]
